---
http:
  routers:
    gnoweb:
      service: gnoweb
      rule: "Host(`portal.gnoteam.com`)"
      # rule: "Host(`portal.gno.land`) || Host(`portal.gnoteam.com`)"
      tls:
        certResolver: le
      entrypoints: ["web", "websecure"]
      middlewares: []

  services:
    gnoweb:
      loadBalancer:
        servers:
          - url: "http://localhost:8888"
