version: "3"

networks:
  portal-loop:
    name: portal-loop
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.0.0/16

services:
  traefik:
    image: "traefik:v2.10"
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/configs"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.rpc.address=:26657"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.traefik.address=:8080"

      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=dev@gno.land"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    networks:
      - portal-loop
    ports:
      - "80:80"
      - "443:443"
      - "26657:26657"
    volumes:
      - ./traefik:/etc/traefik/configs
      - ./traefik/letsencrypt:/letsencrypt

  gnoweb:
    image: ghcr.io/gnolang/gno/gnoweb-slim
    restart: unless-stopped
    entrypoint:
      - gnoweb
      - --bind=0.0.0.0:8888
      - --remote=traefik:26657
      # - --faucet-url="http://faucet.portal.gno.local:26657"
      # - --faucet-url
      # - "http://localhost:9000"
      - --help-chainid
      - --with-analytics
      - portal-loop
      - --help-remote
      - https://rpc.gno.land:443
    networks:
      - portal-loop
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # gnofaucet:
  #   image: gnofaucet
  #   command:
  #     -
  #   environment:
  #     - VIRTUAL_HOST=faucet.test3.gno.land
  #     - VIRTUAL_PORT=5050
  #     - LETSENCRYPT_HOST=faucet.test3.gno.land
  #     # from .env
  #     - RECAPTCHA_SECRET_KEY
  #     - FAUCET_WORDS
  #     - GNOKEY_PASS
  #   ports:
  #     - 5050

  portalloopd:
    image: ghcr.io/gnolang/gno/portalloopd
    restart: unless-stopped
    volumes:
      - ./scripts:/scripts
      - ./backups:/backups
      - ./traefik:/etc/traefik/configs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - portal-loop
    ports:
      - 127.0.0.1:9090:9090
    environment:
      HOST_PWD: $PWD
      BACKUP_DIR: "/backups"
      RPC_URL: "http://traefik:26657"
      PROM_ADDR: "0.0.0.0:9090"
      TRAEFIK_GNO_FILE: "/etc/traefik/configs/gno.yml"
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    command: --interval 30 --http-api-metrics --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_HTTP_API_TOKEN: "mytoken"
    ports:
      - 127.0.0.1:8000:8080
